@echo off
echo Removing .git directory...
rd /s /q .git
echo Initializing new git repository...
git init
echo Adding files (excluding ignored)...
git add .
echo Committing...
git commit -m "Initial commit (fresh start)"
echo Adding remote...
git remote add origin https://github.com/calisweetleaf/Reinforcement-Learning-Full-Pipeline.git
echo Pushing...
git branch -M main
git push -u origin main --force
